package objects;

public enum ProvinceTerritories {
YUKON, NORTHWESTERRITORIES, NUNAVUT, BRITISHCOLOMBIA, ALBERTA, SASKACHEWAN, MANITOBA, ONTARIO, QUEBEC, NEWFOUNDLAND, PRINCEEDWARDISLAND, NEWBRUNSWICK, NOVASCOTIA
}

